root /static;
include  /etc/nginx/mime.types;

location / {
    try_files $uri $uri/ /index.html;
}

location ~* ^.+\.(jpg|jpeg|gif|png|webp|avif|ico)$ {
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
}

location ~* ^.+\.svg$ {
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Vary "Accept-Encoding";

    gzip_static on;
    brotli_static on;
}

location ~* ^.+\.(css|js|woff|woff2|ttf|eot)$ {
    access_log off;
    expires 1y;
    add_header Cache-Control "public, immutable";
    add_header Vary "Accept-Encoding";
    
    gzip_static on;
    brotli_static on;
}

location ~* ^.+\.(pdf|txt|xml|json)$ {
    access_log off;
    expires 30d;
    add_header Cache-Control "public";
    add_header Vary "Accept-Encoding";
    
    gzip_static on;
    brotli_static on;
}

location ~* ^(.+\.html|.*/)$ {
    expires 1d;
    add_header Cache-Control "public, must-revalidate";
    etag on;
    
    gzip_static on;
    brotli_static on;
}

location ~* \.(map|log)$ {
    deny all;
}

client_max_body_size 1m;
